version: "3.9"

services:
  app:
    build:
      context: .
    container_name: django-blog-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "sleep infinity"